name: build and publish

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/jakewharton/gitout
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1.0.3
        if: "!startsWith(github.event.ref, 'refs/tags')"
        with:
          command: publish
          args: --dry-run

      - uses: actions-rs/cargo@v1.0.3
        if: "startsWith(github.event.ref, 'refs/tags')"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: publish
